# Generated by Django 4.1.2 on 2022-10-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_customerreportrecord_time_raised'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReportRecord',
        ),
    ]
